const country = [
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Belgium",
    "Bolivia",
    "Brazil",
    "Bulgaria",
    "Canada",
    "Chile",
    "China",
    "Croatia",
    "Czech Republic",
    "England",
    "France",
    "Georgian Republic",
    "Germany",
    "Greece",
    "Hungary",
    "Israel",
    "Italy",
    "Japan",
    "Lebanon",
    "Liechtenstein",
    "Luxembourg",
    "Mexico",
    "Moldova",
    "Morocco",
    "Netherlands",
    "New Zealand",
    "Peru",
    "Poland",
    "Portugal",
    "Romania",
    "Slovakia",
    "Slovenia",
    "South Africa",
    "Spain",
    "Switzerland",
    "Syria",
    "Turkey",
    "USA",
    "Ukraine",
    "Uruguay"
];

export default country.map((val, idx) => {
    return {
        value: idx,
        label: val
    }
});