const grapes = [
    "Abouriou",
    "Acolon",
    "Agiorgitiko",
    "Aglianico",
    "Aglianico - Piedirosso",
    "Airen",
    "Aladasturi",
    "Albalonga",
    "Albana",
    "Albanella",
    "Albarin Blanco",
    "Albarino (Alvarinho)",
    "Albarola",
    "Albarola - Bosco - Vermentino",
    "Albarossa",
    "Albillo",
    "Aleatico",
    "Alfrocheiro Preto",
    "Alfrocheiro Preto - Tinta Roriz - Touriga",
    "Alfrocheiro Preto - Touriga",
    "Alicante Bouschet",
    "Alicante Bouschet - Aragonez",
    "Alicante Bouschet - Aragonez - Trincadeira",
    "Alicante Bouschet - Touriga",
    "Aligote",
    "Altesse",
    "Alvarelhao",
    "Amigne",
    "Antao Vaz",
    "Antao Vaz - Arinto (Pederna)",
    "Aragonez (Tinta Roriz) - Castelao",
    "Aramon",
    "Arbois",
    "Areni Noir",
    "Arinto (Pederna)",
    "Arinto (Pederna) - Fernao Pires",
    "Arinto (Pederna) - Loureiro",
    "Arneis",
    "Aspiran",
    "Assyrtiko",
    "Auxerrois",
    "Avesso",
    "Avgoustiatis",
    "Azal Branco",
    "Babeasca Neagra",
    "Babic",
    "Baco Blanc",
    "Baga",
    "Barbarossa",
    "Barbera",
    "Barbera - Bonarda (Croatina)",
    "Barbera - Dolcetto - Nebbiolo",
    "Barbera - Nebbiolo",
    "Barbera - Sangiovese",
    "Barsaglina",
    "Bellone Bianco",
    "Bianchetta Genovese",
    "Biancolella",
    "Biancone",
    "Biancu Gentile",
    "Bical",
    "Blauer Wildbacher",
    "Blaufrankisch (Lemberger)",
    "Blaufrankisch - Cabernet",
    "Blaufrankisch - Cabernet - Merlot",
    "Blaufrankisch - Zweigelt",
    "Bobal",
    "Bombino Bianco",
    "Bombino Nero",
    "Bonarda - Malbec",
    "Bonarda Piemontese",
    "Bordeaux Blend Red",
    "Bordeaux Blend White",
    "Bourboulenc",
    "Bouvier",
    "Brachetto",
    "Braquet",
    "Bronner",
    "Brunal",
    "Bual (Malvasia Fina)",
    "Cab Franc - Gamay - Malbec",
    "Cabernet - Carignan - Grenache",
    "Cabernet - Carignan - Syrah",
    "Cabernet - Grenache - Merlot - Syrah",
    "Cabernet - Grenache - Mourvedre - Syrah",
    "Cabernet - Grenache - Syrah",
    "Cabernet - Malbec - Syrah",
    "Cabernet - Merlot - Montepulciano",
    "Cabernet - Merlot - Sangiovese",
    "Cabernet - Merlot - Syrah",
    "Cabernet - Merlot - Tempranillo",
    "Cabernet - Merlot - Zinfandel",
    "Cabernet - Merlot - Zweigelt",
    "Cabernet - Montepulciano",
    "Cabernet - Mourvedre - Syrah",
    "Cabernet - Nero d'Avola",
    "Cabernet - Petit Verdot",
    "Cabernet - Sangiovese",
    "Cabernet - Sangiovese - Syrah",
    "Cabernet - Syrah - Tempranillo",
    "Cabernet - Syrah - Zinfandel",
    "Cabernet - Syrah/Shiraz",
    "Cabernet - Tannat",
    "Cabernet - Tempranillo",
    "Cabernet - Zinfandel",
    "Cabernet Cubin",
    "Cabernet Franc",
    "Cabernet Franc - Cabernet Sauvignon",
    "Cabernet Franc - Gamay",
    "Cabernet Franc - Malbec",
    "Cabernet Franc - Merlot",
    "Cabernet Franc - Pinot Noir",
    "Cabernet Sauvignon",
    "Cabernet Sauvignon - Carignan",
    "Cabernet Sauvignon - Carmenere",
    "Cabernet Sauvignon - Cinsault",
    "Cabernet Sauvignon - Malbec",
    "Cabernet Sauvignon - Merlot",
    "Cabernet Sauvignon - Pinot Noir",
    "Cabernets - Grolleau",
    "Cagnulari",
    "Caino Tinto",
    "Caladoc",
    "Callet",
    "Camaralet de Lasseube",
    "Canaiolo",
    "Carcajolo Nero",
    "Carignan (Carinena)",
    "Carignan - Grenache - Syrah",
    "Carignan - Grenache - Tempranillo",
    "Carignan - Merlot",
    "Carignan - Syrah",
    "Carignan Blanc",
    "Carignan Gris",
    "Carinena - Garnacha",
    "Carmenere",
    "Carmenere - Syrah",
    "Carminoir",
    "Carrasquin",
    "Carricante",
    "Carricante - Catarratto",
    "Casavecchia",
    "Castelao",
    "Castelao - Touriga",
    "Castets",
    "Catarratto",
    "Catarratto - Chardonnay",
    "Catarratto - Grillo - Inzolia",
    "Catarratto - Inzolia",
    "Cava Blend",
    "Cayetana",
    "Cerceal",
    "Cesanese",
    "Cesar",
    "Champagne Blend",
    "Charbono (Bonarda)",
    "Chardonel",
    "Chardonnay",
    "Chardonnay - Chenin Blanc",
    "Chardonnay - Garganega",
    "Chardonnay - Gewurztraminer",
    "Chardonnay - Muscat",
    "Chardonnay - Pinot Blanc",
    "Chardonnay - Pinot Blanc - Pinot Noir",
    "Chardonnay - Pinot Gris",
    "Chardonnay - Pinot Noir",
    "Chardonnay - Riesling",
    "Chardonnay - Roussanne",
    "Chardonnay - Roussanne - Viognier",
    "Chardonnay - Sauvignon - Semillon",
    "Chardonnay - Sauvignon Blanc",
    "Chardonnay - Savagnin",
    "Chardonnay - Semillon",
    "Chardonnay - Verdelho",
    "Chardonnay - Vermentino",
    "Chardonnay - Viognier",
    "Chardonnay - Viura",
    "Chardonnay - Xarel-lo",
    "Chardonnay Musque",
    "Chardonnay Rose",
    "Chasselas",
    "Chenin Blanc",
    "Chianti Blend",
    "Chinuri",
    "Ciliegiolo",
    "Cinsault",
    "Cinsault - Grenache",
    "Cinsault - Grenache - Mourvedre",
    "Cinsault - Grenache - Syrah",
    "Cinsault - Mourvedre",
    "Cinsault - Mourvedre - Syrah",
    "Cinsault - Syrah",
    "Clairette",
    "Clairette - Marsanne - Ugni",
    "Clairette - Muscat",
    "Clairette - Ugni Blanc",
    "Coda di Volpe",
    "Codega do Larinho",
    "Colombard",
    "Colombard - Ugni Blanc",
    "Colorino",
    "Completer",
    "Concord",
    "Corinto Nero",
    "Cornalin",
    "Cortese",
    "Corvina",
    "Corvina - Rondinella",
    "Counoise",
    "Criolla Grande",
    "Croatina",
    "Cserszegi Fuszeres",
    "Diolinoir",
    "Dolcetto",
    "Dona Blanca",
    "Donzelinho Branco",
    "Doral",
    "Dornfelder",
    "Dunaj",
    "Duras",
    "Durella",
    "Durif - Shiraz",
    "Durize",
    "Edelzwicker Blend",
    "Elbling",
    "Encruzado",
    "Erbaluce",
    "Espadeiro",
    "Ezerjo",
    "Falanghina",
    "Fer Servadou",
    "Fernao Pires",
    "Feteasca Neagra",
    "Fiano",
    "Folgasao",
    "Folle Blanche",
    "Forastera",
    "Fortana",
    "Frappato",
    "Frappato - Nero d'Avola",
    "Freisa",
    "Freisamer",
    "Friulano",
    "Fruhburgunder",
    "Fruhroter Veltliner",
    "Fumin",
    "Furmint",
    "Gaglioppo",
    "Gamaret",
    "Gamaret - Garanoir",
    "Gamaret - Garanoir - Pinot Noir",
    "Gamay",
    "Gamay - Grolleau Noir",
    "Gamay - Pinot Noir",
    "Gamay - Poulsard",
    "Garanoir",
    "Garganega",
    "Garnacha - Tempranillo",
    "Gewurztraminer",
    "Gewurztraminer - Riesling",
    "Giro",
    "Glera (Prosecco)",
    "Glera - Pinot Noir",
    "Godello",
    "Goldburger",
    "Gouveio",
    "Graciano",
    "Grechetto",
    "Greco",
    "Greco Bianco",
    "Grenache (Garnacha)",
    "Grenache - Merlot - Syrah",
    "Grenache - Mourvedre",
    "Grenache - Mourvedre - Syrah",
    "Grenache - Sangiovese",
    "Grenache - Syrah",
    "Grenache Blanc",
    "Grenache Blanc - Grenache Gris",
    "Grenache Blanc - Vermentino",
    "Grenache Gris",
    "Grignolino",
    "Grillo",
    "Gringet",
    "Grolleau Gris",
    "Grolleau Noir",
    "Groppello",
    "Gros Manseng",
    "Gros Manseng - Petit Manseng",
    "Gros Manseng - Sauvignon Blanc",
    "Gruner Veltliner",
    "Harslevelu",
    "Hondarrabi Beltza",
    "Hondarrabi Zuri",
    "Humagne Blanche",
    "Humagne Rouge",
    "Huxelrebe",
    "Inzolia",
    "Irsay Oliver",
    "Isabella",
    "Jacquere",
    "Johanniter",
    "Juan Garcia",
    "Juhfark",
    "Jurancon Noir (Folle Noire)",
    "Kadarka Blau",
    "Keknyelu",
    "Kerner",
    "Kisi",
    "Koshu",
    "Krakhuna",
    "Lacrima",
    "Lagrein",
    "Lambrusco",
    "Leanyka",
    "Len de l'El - Mauzac",
    "Limniona",
    "Listan Negro",
    "Lledoner Pelut",
    "Loureiro",
    "Macabeo (Viura)",
    "Macabeo - Parellada - Xarel-lo",
    "Magliocco Canino",
    "Malagousia",
    "Malbec",
    "Malbec - Merlot",
    "Malbec - Merlot - Tannat",
    "Malbec - Syrah",
    "Malbo Gentile",
    "Malvar",
    "Malvasia",
    "Malvasia - Trebbiano",
    "Malvasia Bianca",
    "Malvasia Istriana",
    "Malvasia Nera",
    "Malvasia Nera - Negroamaro",
    "Malvasia di Candia",
    "Mandilaria (Amorghiano)",
    "Mansengs - Petit Courbu",
    "Manto Negro",
    "Mantonico Bianco",
    "Manzoni Bianco",
    "Mara",
    "Marmajuelo",
    "Marsanne",
    "Marsanne - Roussanne",
    "Marselan",
    "Marzemino",
    "Maturana Blanca",
    "Mauzac",
    "Mavro",
    "Mavrodaphne",
    "Mavrotragano",
    "Mayolet",
    "Melon Queue Rouge",
    "Melon de Bourgogne",
    "Mencia",
    "Meritage",
    "Merlot",
    "Merlot - Montepulciano",
    "Merlot - Nero d'Avola",
    "Merlot - Sagrantino - Sangiovese",
    "Merlot - Sangiovese",
    "Merlot - Sangiovese - Syrah",
    "Merlot - Syrah",
    "Merlot - Tannat",
    "Merlot - Tempranillo",
    "Merlot Blanc",
    "Merseguera",
    "Merwah",
    "Minnella",
    "Molinara",
    "Moll",
    "Monastrell - Tempranillo",
    "Mondeuse Blanche",
    "Mondeuse Noire",
    "Monica",
    "Montepulciano",
    "Montepulciano - Sangiovese",
    "Montepulciano - Syrah",
    "Montonega",
    "Moreto",
    "Moristel",
    "Moscato Giallo",
    "Moscato Rosa",
    "Moschofilero",
    "Mourisco Tinto",
    "Mourvedre (Monastrell)",
    "Mourvedre - Syrah",
    "Mtsvane",
    "Mtsvane Kakhuri",
    "Muller-Thurgau",
    "Muscadelle",
    "Muscat",
    "Muscat Blanc a Petits Grains",
    "Muscat Hamburg (Muskat Trollinger)",
    "Muscat Ottonel",
    "Muscat of Alexandria",
    "Nascetta",
    "Nasco",
    "Nebbiolo",
    "Negoska",
    "Negramoll",
    "Negrette",
    "Negroamaro",
    "Negroamaro - Primitivo",
    "Nerello Cappuccio",
    "Nerello Cappuccio - Nerello Mascalese",
    "Nerello Mascalese",
    "Nero Buono",
    "Nero d'Avola",
    "Nero d'Avola - Syrah",
    "Neuburger",
    "Niagara",
    "Nielluccio - Sciaccarello",
    "Nocera",
    "Nosiola",
    "Nuragus",
    "Obaideh",
    "Ojaleshi",
    "Ondenc",
    "Orleans",
    "Ortega",
    "Orvieto Blend",
    "Oseleta",
    "Pais (Mission)",
    "Palava",
    "Pallagrello Bianco",
    "Pallagrello Nero",
    "Palomino",
    "Parellada",
    "Parraleta (Tinta Caiada)",
    "Passerina",
    "Passerina - Pecorino - Trebbiano",
    "Pecorino",
    "Pedro Ximenez",
    "Pelaverga",
    "Perricone",
    "Persan",
    "Petit Courbu",
    "Petit Manseng",
    "Petit Meslier",
    "Petit Rouge",
    "Petit Verdot",
    "Petite Arvine",
    "Petite Sirah (Durif)",
    "Petite Sirah - Zinfandel",
    "Picolit",
    "Picpoul",
    "Picpoul Noir",
    "Piedirosso",
    "Pignolo",
    "Pineau d'Aunis",
    "Pinella (Pinello)",
    "Pinot - Poulsard - Trousseau",
    "Pinot Blanc",
    "Pinot Blanc - Pinot Noir",
    "Pinot Gris/Grigio",
    "Pinot Gris/Grigio - Pinot Blanc",
    "Pinot Meunier",
    "Pinot Meunier - Pinot Noir",
    "Pinot Noir",
    "Pinot Noir - Syrah",
    "Pinot Noir - Zweigelt",
    "Pinot d'Alsace",
    "Pinotage",
    "Planta Nova",
    "Plavac Mali",
    "Pollera Nera",
    "Port Blend Red",
    "Port Blend White",
    "Portugieser",
    "Portuguese Red Blend",
    "Portuguese White Blend",
    "Posip",
    "Poulsard",
    "Premetta",
    "Prieto Picudo",
    "Primitivo",
    "Prunelard Noir",
    "Pugnitello",
    "Rabigato",
    "Rabo de Ovelha",
    "Raboso",
    "Ramisco",
    "Rauschling",
    "Rebo",
    "Red Blend",
    "Refosco",
    "Regent",
    "Ribolla Gialla",
    "Rieslaner",
    "Riesling",
    "Riesling - Silvaner",
    "Rioja Red Blend",
    "Rioja White Blend",
    "Rkatsiteli",
    "Rkatsiteli - Mtsvane",
    "Robola",
    "Roditis",
    "Rolle - Ugni Blanc",
    "Romorantin",
    "Roscetto",
    "Rose Blend",
    "Rossese",
    "Rotberger",
    "Roter Traminer (Savagnin Rose)",
    "Roter Veltliner",
    "Rotgipfler",
    "Rotgipfler - Zierfandler",
    "Roussanne",
    "Roussanne - Viognier",
    "Ruche",
    "Rufete (Tinta Pinheira)",
    "Sacy",
    "Sagrantino",
    "Sagrantino - Sangiovese",
    "Saint-Croix",
    "Sangiovese",
    "Sangiovese - Syrah",
    "Sankt Laurent",
    "Saperavi",
    "Sauvignon Blanc",
    "Sauvignon Blanc - Semillon",
    "Sauvignon Blanc - Ugni Blanc",
    "Sauvignon Blanc - Verdejo",
    "Sauvignon Blanc - Vermentino",
    "Sauvignon Blanc - Viognier",
    "Sauvignon Gris",
    "Savagnin",
    "Savatiano",
    "Scheurebe",
    "Schiava",
    "Schioppettino",
    "Sciaccarello (Mammolo)",
    "Semillon",
    "Semillon - Rolle",
    "Sercial",
    "Seyval Blanc",
    "Sherry Blend",
    "Shiraz and Syrah",
    "Sideritis",
    "Silvaner",
    "Siria (Roupeiro)",
    "Soave Blend",
    "Solaris",
    "Southern Rhone Red Blend",
    "Southern Rhone White Blend",
    "Souvignier Gris",
    "Spergola",
    "Steuben",
    "Sumoll",
    "Sumoll Blanco",
    "Susumaniello",
    "Syrah - Tempranillo",
    "Syrah - Touriga",
    "Syrah - Viognier",
    "Syrah - Zinfandel",
    "Tannat",
    "Tazzelenghe",
    "Tempranillo",
    "Tempranillo Blanco",
    "Teran",
    "Teroldego",
    "Terrantez",
    "Terret Blanc",
    "Terret Gris",
    "Terret Noir",
    "Tibouren",
    "Timorasso",
    "Tinta Amarela (Trincadeira)",
    "Tinta Barroca",
    "Tinta Barroca - Tinta Roriz - Touriga",
    "Tinta Carvalha",
    "Tinta Francisca",
    "Tinta Negra Mole",
    "Tinta Roriz (Aragonez) - Touriga",
    "Tinta Roriz - Tinto Cao - Touriga",
    "Tintilia",
    "Tinto Cao",
    "Tintore di Tramonti",
    "Tokaji Blend",
    "Torbato",
    "Torrontes",
    "Touriga Franca",
    "Touriga Franca - Touriga Nacional",
    "Touriga Nacional",
    "Trajadura (Treixadura)",
    "Traminer",
    "Trebbiano (Ugni Blanc)",
    "Trebbiano Spoletino",
    "Trepat",
    "Trincadeira das Pratas",
    "Trousseau (Bastardo)",
    "Trousseau Gris",
    "Tsaoussi",
    "Tsitska",
    "Tsolikouri",
    "Uva di Troia",
    "Valpolicella Blend",
    "Verdea - Colombana",
    "Verdeca",
    "Verdejo",
    "Verdejo - Viura",
    "Verdelho",
    "Verdicchio",
    "Verdoncho",
    "Verduzzo",
    "Vermentino (Rolle)",
    "Vermentino Nero",
    "Vernaccia",
    "Vernaccia Nera",
    "Vertzami",
    "Vespaiolo",
    "Vespolina",
    "Vidal",
    "Vijariego Blanco",
    "Vijariego Negro",
    "Vinhao (Sousao)",
    "Viognier",
    "Viorica",
    "Viosinho",
    "Vital",
    "Vitovska",
    "Vugava",
    "Welschriesling",
    "White Blend",
    "Xarel-lo",
    "Xarel-lo Vermell",
    "Xinomavro",
    "Zefir",
    "Zelen",
    "Zenit",
    "Zeus",
    "Zierfandler",
    "Zinfandel",
    "Zweigelt"
];

export default grapes.map((val, idx) => {
    return {
        value: idx,
        label: val
    }
});