const region = [
    "Aargau",
    "Abruzzo",
    "Aconcagua Valley",
    "Aegean Islands",
    "Aegean",
    "Ahr",
    "Alentejo Region",
    "Algarve Region",
    "Alsace",
    "Andalucia",
    "Aosta Valley",
    "Aragatsotn",
    "Aragon",
    "Armagnac",
    "Asturias",
    "Atacama",
    "Attika",
    "Auckland",
    "Azores Region",
    "Badacsony",
    "Baden",
    "Bairrada Region",
    "Baja California",
    "Balaton-felvidek",
    "Balatonboglar",
    "Balatonfured-Csopak",
    "Balearic Islands",
    "Basilicata",
    "Batroun",
    "Beaujolais",
    "Beira Interior Region",
    "Beiras",
    "Bekaa Valley",
    "Bento Goncalves",
    "Bio Bio Valley",
    "Bordeaux",
    "British Columbia",
    "Burgenland",
    "Burgundy",
    "Cachapoal Valley",
    "Calabria",
    "California",
    "Campanha",
    "Campania",
    "Canary Islands",
    "Canelones",
    "Cantabria",
    "Canterbury",
    "Caribbean",
    "Carnuntum",
    "Casablanca Valley",
    "Castilla La Mancha",
    "Castilla y Leon",
    "Catalonia [Catalunya]",
    "Cava",
    "Central Otago",
    "Central Valley - Chile",
    "Champagne",
    "Colchagua Valley",
    "Cornwall",
    "Corsica",
    "Coteaux du Lyonnais",
    "Crete",
    "Crimea",
    "Curico Valley",
    "Dalmacija",
    "Dalmatinska Zagora",
    "Danubian Plains",
    "Dao Region",
    "Douro Region",
    "Eger",
    "Elqui Valley",
    "Emilia-Romagna",
    "Etyek-Buda",
    "Extremadura",
    "Franken",
    "Friuli-Venezia Giulia",
    "Galicia",
    "Galilee",
    "Geneva",
    "Graubunden",
    "Hajos-Baja",
    "Hawke's Bay",
    "Hessische Bergstrasse",
    "IGP Stefan Voda",
    "IGP Valul lui Traian",
    "Ica Valley",
    "Imereti",
    "Ionian Islands",
    "Island of Hvar",
    "Istria",
    "Itata Valley",
    "Juanico",
    "Judean Hills",
    "Jura",
    "Juznoslovenska",
    "Kakheti",
    "Kamptal",
    "Kartli",
    "Kent",
    "Kontinentalna Hrvatska",
    "Kremstal",
    "Kunsag",
    "La Rioja",
    "Languedoc-Roussillon",
    "Lazio",
    "Leyda Valley",
    "Liguria",
    "Limari Valley",
    "Lisboa Region",
    "Loire",
    "Lombardy",
    "Macedonia - Greece",
    "Madeira Region",
    "Madrid",
    "Maipo Valley",
    "Maldonado",
    "Malleco Valley",
    "Malokarpatska",
    "Marche",
    "Marlborough",
    "Martinborough",
    "Matra",
    "Maule Valley",
    "Mendoza",
    "Mittelrhein",
    "Molise",
    "Montevideo",
    "Moravia",
    "Mor",
    "Moselle - Luxembourg",
    "Moselle",
    "Mosel",
    "Murcia",
    "Nagy Somlo",
    "Nahe",
    "Navarra",
    "Negev",
    "Nelson",
    "Neszmely",
    "Neuchatel - Three Lakes",
    "New South Wales",
    "Niederosterreich [Lower Austria]",
    "Ningxia",
    "Nitrianska",
    "Ontario",
    "Oregon",
    "Pais Vasco",
    "Pannonhalma",
    "Patagonia",
    "Pecs",
    "Peljesac Peninsula",
    "Peloponnese",
    "Peninsula de Setubal Region",
    "Pfalz",
    "Piedmont [Piemonte]",
    "Podravje",
    "Primorska Hrvatska",
    "Primorski",
    "Progreso",
    "Provence",
    "Puglia",
    "Racha-Lechkhumi",
    "Rapel Valley",
    "Retsina",
    "Rheingau",
    "Rheinhessen",
    "Rhone",
    "Rioja",
    "Saale-Unstrut",
    "Sachsen",
    "Salta",
    "San Antonio Valley - Chile",
    "San Juan",
    "Sardinia",
    "Savoie",
    "Schaffhausen",
    "Setubal Peninsula",
    "Sicily",
    "Sopron",
    "South Australia",
    "South Eastern Australia",
    "South West France",
    "Srednja I Juzna Dalmacija",
    "St. Gallen - Rheintal",
    "Steiermark",
    "Sussex",
    "Szekszard",
    "Tarija",
    "Tasmania",
    "Tavora-Varosa Region",
    "Tejo Region",
    "Thermenregion",
    "Thessalia",
    "Thracian Lowlands",
    "Thurgau",
    "Ticino [Tessin]",
    "Tokaj",
    "Traisental",
    "Tras-os-Montes Region",
    "Trentino-Alto Adige",
    "Tuscany",
    "Umbria",
    "Valais",
    "Valencia",
    "Valle de Guadalupe",
    "Vaud",
    "Vayots Dzor",
    "Veneto",
    "Victoria",
    "Vienna",
    "Villany",
    "Vin de France - Vin de Table",
    "Vin de Pays - IGP",
    "Vinho Verde Region",
    "Vino d'Italia - Vino da Tavola",
    "Vinos de Pago",
    "Wachau",
    "Wagram",
    "Waiheke Island",
    "Wairarapa",
    "Washington",
    "Weinviertel",
    "Western Australia",
    "Western Cape",
    "Wurttemberg",
    "Yamanashi",
    "Yunnan",
    "Zurich",
    "delle Venezie"
];

export default region.map((val, idx) => {
    return {
        value: idx,
        label: val
    }
});